package com.example.employee.entity;

public class Employee {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.employee_id
	 * @mbggenerated  Fri Sep 22 13:44:00 MMT 2017
	 */
	private Long employeeId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.employee_name
	 * @mbggenerated  Fri Sep 22 13:44:00 MMT 2017
	 */
	private String employeeName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.address
	 * @mbggenerated  Fri Sep 22 13:44:00 MMT 2017
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.gender
	 * @mbggenerated  Fri Sep 22 13:44:00 MMT 2017
	 */
	private String gender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.remark
	 * @mbggenerated  Fri Sep 22 13:44:00 MMT 2017
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.email
	 * @mbggenerated  Fri Sep 22 13:44:00 MMT 2017
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.password
	 * @mbggenerated  Fri Sep 22 13:44:00 MMT 2017
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.phone
	 * @mbggenerated  Fri Sep 22 13:44:00 MMT 2017
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column employee.role
	 * @mbggenerated  Fri Sep 22 13:44:00 MMT 2017
	 */
	private String role;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.employee_id
	 * @return  the value of employee.employee_id
	 * @mbggenerated  Fri Sep 22 13:44:00 MMT 2017
	 */
	public Long getEmployeeId() {
		return employeeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.employee_id
	 * @param employeeId  the value for employee.employee_id
	 * @mbggenerated  Fri Sep 22 13:44:00 MMT 2017
	 */
	public void setEmployeeId(Long employeeId) {
		this.employeeId = employeeId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.employee_name
	 * @return  the value of employee.employee_name
	 * @mbggenerated  Fri Sep 22 13:44:00 MMT 2017
	 */
	public String getEmployeeName() {
		return employeeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.employee_name
	 * @param employeeName  the value for employee.employee_name
	 * @mbggenerated  Fri Sep 22 13:44:00 MMT 2017
	 */
	public void setEmployeeName(String employeeName) {
		this.employeeName = employeeName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.address
	 * @return  the value of employee.address
	 * @mbggenerated  Fri Sep 22 13:44:00 MMT 2017
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.address
	 * @param address  the value for employee.address
	 * @mbggenerated  Fri Sep 22 13:44:00 MMT 2017
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.gender
	 * @return  the value of employee.gender
	 * @mbggenerated  Fri Sep 22 13:44:00 MMT 2017
	 */
	public String getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.gender
	 * @param gender  the value for employee.gender
	 * @mbggenerated  Fri Sep 22 13:44:00 MMT 2017
	 */
	public void setGender(String gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.remark
	 * @return  the value of employee.remark
	 * @mbggenerated  Fri Sep 22 13:44:00 MMT 2017
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.remark
	 * @param remark  the value for employee.remark
	 * @mbggenerated  Fri Sep 22 13:44:00 MMT 2017
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.email
	 * @return  the value of employee.email
	 * @mbggenerated  Fri Sep 22 13:44:00 MMT 2017
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.email
	 * @param email  the value for employee.email
	 * @mbggenerated  Fri Sep 22 13:44:00 MMT 2017
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.password
	 * @return  the value of employee.password
	 * @mbggenerated  Fri Sep 22 13:44:00 MMT 2017
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.password
	 * @param password  the value for employee.password
	 * @mbggenerated  Fri Sep 22 13:44:00 MMT 2017
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.phone
	 * @return  the value of employee.phone
	 * @mbggenerated  Fri Sep 22 13:44:00 MMT 2017
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.phone
	 * @param phone  the value for employee.phone
	 * @mbggenerated  Fri Sep 22 13:44:00 MMT 2017
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column employee.role
	 * @return  the value of employee.role
	 * @mbggenerated  Fri Sep 22 13:44:00 MMT 2017
	 */
	public String getRole() {
		return role;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column employee.role
	 * @param role  the value for employee.role
	 * @mbggenerated  Fri Sep 22 13:44:00 MMT 2017
	 */
	public void setRole(String role) {
		this.role = role;
	}
}